[package]
name = "waybar-taskwarrior"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
chrono-humanize = "0.2.3"
icu = "1.5.0"
parse_datetime = "0.6.0"
prettytable-rs = "0.10.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
itertools = "0.14.0"
paste = "1.0"
